"""Initial migration

Revision ID: 107817e0ed56
Revises: 
Create Date: 2025-03-12 16:39:01.798417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '107817e0ed56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('user', 'doctor', 'moderator', 'pharmacist', 'admin', name='user_role'),
               nullable=True,
               existing_server_default=sa.text("'user'::user_role"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('user', 'doctor', 'moderator', 'pharmacist', 'admin', name='user_role'),
               nullable=False,
               existing_server_default=sa.text("'user'::user_role"))

    # ### end Alembic commands ###
