"""PCOSPrediction MOdel creation

Revision ID: f66f2ba4e88e
Revises: 188d0c4a3762
Create Date: 2025-05-14 10:33:03.374053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66f2ba4e88e'
down_revision = '188d0c4a3762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcos_predictions', schema=None) as batch_op:
        batch_op.drop_column('recommendation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcos_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
